resulttype:
 numbers: "323,2"
 type: "323_Mid Term,323_Final Term,323_Class 10 Mid Term,323_Class 10 Final Term,2_Final Term,2_First Term,2_Mock Test,2_Quarter" 
 default: "Type 1,Type 2,Type 3,Type 4"
resulttype2:
 numbers: "323,2"
 type: "323_5_Mock Test,323_3_Term,323_2_Project,323_1_Class Test,2_5_Mock Test,2_3_Term,2_2_Project,2_1_Class Test,2_4_Surprise Test" 
 default: "4_Surprise Test,3_Term,2_Project,1_Class Test"
mocktest:
 numbers: "2"
