resulttype:
 numbers: "323,2,325,340,312,348,3,352,346,355,356,324,357"
 type_323: "Mid Term,Final Term,Class 10 Mid Term,Class 10 Final Term,Class Test,Final Term Legal,Assessment,Mid Term New,Final Term Covid,Assessment Final"
 type_325: "Summer,Spring,Fall,Test,Final"
 type_356: "Type1,Type2,Type3"
 type_2: "Final Term,First Term,Mock Test,Quarter,KG First Term,KG Final Term"
 type_3: "Term Exam"
 type_319: "Senior Section Quarter,Type 2,Type 3,Junior Section Quarter,Type 5,Type 6,Type 7,Type 8, Type 9"
 type_357: "Term(N-KG),AR(N-KG),Term(class 1-class 5),AR(class 1-class 5),Term(class 6-class 7),AR(class 6-class 7),Term(class 8-class 10),AR(class 8-class 10),Term(class 11-class 12),AR(class 11-class 12),Pre Test(class 10 12),Pre Test(class 5 8),Quiz Exam(class 11-12),Quiz Exam(class 1-8),Quiz Exam(class 9-10),Remarks Assessment,Tabulation,Remarks Only"
 type_324: "Term(N-KG),AR(N-KG),Term(class 1-class 5),AR(class 1-class 5),Term(class 6-class 7),AR(class 6-class 7),Term(class 8-class 10),AR(class 8-class 10),Term(class 11-class 12),AR(class 11-class 12),Pre Test(class 10 12),Pre Test(class 5 8)"
 type_346: "Term(N-KG),AR(N-KG),Term(class 1-class 5),AR(class 1-class 5),Term(class 6-class 7),AR(class 6-class 7),Term(class 8-class 10),AR(class 8-class 10),Term(class 11-class 12),AR(class 11-class 12),Pre Test(class 10 12),Pre Test(class 5 8)"
 type_352: "Term(N-KG),AR(N-KG),Term(class 1-class 5),AR(class 1-class 5),Term(class 6-class 7),AR(class 6-class 7),Term(class 8-class 10),AR(class 8-class 10),Term(class 11-class 12),AR(class 11-class 12),Pre Test(class 10 12),Pre Test(class 5 8),Online Exam(covid),Online Exam Higher Class(covid),Online Exam(class 8)"
 type_312: "Final Term,First Term,Mock Test,Quarter,KG First Term,KG Final Term,Mock Exam Final,Term New,Quarter New,Final Term Exam Covid,Final Term (I-II) Exam Covid,Quarter Online Exam,Half Yearly Online Exam(Junior),Half Yearly Online Exam(Senior),Half Yearly Online Exam(9-12)"
 type_348: "QUARTER(PG),QUARTER(NURSERY),QUARTER(KGI-KGII),QUARTER(I-VII),QUARTER(VIII),QUARTER(IX),TERM(PG-N),TERM(KGI-KGII),TERM(I-VIII),MOCK(IX-X),QUARTER January (I-VII),Term January (I-VII),QUARTER(A2-AS),Term Twenty Mark,Board Exam"
 type_340: "QUARTER,TERM (SECOND HALF),TERM (FIRST HALF) EFFORT/GRADE SHEET (CLASS 5-9),TERM EXAM (CLASS 5-9),TERM (FIRST HALF) EFFORT/GRADE SHEET (CLASS 10-12),TERM EXAM (CLASS 10-12),HALL EXAM,FINAL SCORE SHEET,TERM REPORT CARD(CLASS 5-9),FINAL REPORT (CLASS 5-9),TERM REPORT CARD(CLASS 10-12),ASSESMENT(KG 1-CLASS 4),REPORT CARD(KG 1-KG 2),REPORT CARD(CLASS 1-CLASS 4),MOCK TEST"
 type_355: "Junior Section,Senior Section"
 default: "Type 1,Type 2,Type 3,Type 4,Type 5,Type 6,Type 7,Type 8, Type 9"
resulttype2:
 numbers: "323,2,325,340,342,352,348,356,324,357"
 type_357: "1_ME/CW/SBA,2_AT,3_CQ,4_MCQ,5_PR"
 type_340: "1_Class Test,2_Term Test,3_Written,4_Assesment,5_Mock Test"
 type_325: "1_Class Test,2_Project,3_Term,4_Attendance"
 type_323: "1_Class Test,2_Project,3_Term,5_Mock Test,6_Assessment,7_H.W & Assignment,8_C.W OR S.T"
 type_342: "1_Class Test,2_Project,3_Term,5_Mock Test"
 type_348: "1_Class Test,2_Project,3_Term,4_Practical,5_Assessment,6_N/A,7_Group Project"
 type_352: "1_ME/CW/SBA,2_AT,3_SB,4_OB,5_PR"
 type_324: "1_ME/CW/SBA,2_AT,3_SB,4_OB,5_PR"
 type_356: "1_CQ/SQ,2_MCQ,3_MTT/Prac"
 type_2: "1_Class Test,2_Project,3_Term,4_Surprise Test,5_Mock Test" 
 default: "6_N/A,5_Practical,4_Surprise Test,3_Term,2_Project,1_Class Test"
quarter:
 numbers: "325,340,352,324,357"
 type_357: "1_1st Term,2_2nd Term,3_N/A"
 type_352: "1_1st Term,2_2nd Term,3_N/A"
 type_324: "1_1st Term,2_2nd Term,3_N/A"
 type_325: "1_Summer,2_Spring,3_Fall"
 type_348: "0_N/A,1_1st Quarter,2_2nd Quarter,3_3rd Quarter,4_4th Quarter,5_First Term,6_Final Term"
 type_340: "1_TERM 1 (FIRST HALF),2_TERM 1 (SECOND HALF),3_HALF YEARLY,4_TERM 2 (FIRST HALF),5_TERM 2 (SECOND HALF),6_FINAL"
 default: "0_N/A,1_1st Quarter,2_2nd Quarter,3_3rd Quarter,4_4th Quarter,5_First Term,6_Final Term"
mocktest:
 numbers: "2,323,342"
formapply:
 numbers: "2,340"
