resulttype:
 numbers: "323,2,325"
 type: "325_Summer,325_Spring,325_Fall,323_Mid Term,323_Final Term,323_Class 10 Mid Term,323_Class 10 Final Term,2_Final Term,2_First Term,2_Mock Test,2_Quarter" 
 default: "Type 1,Type 2,Type 3,Type 4"
resulttype2:
 numbers: "323,2,325"
 type: "325_1_Class Test,325_2_Project,325_3_Term,325_4_Attendance,323_5_Mock Test,323_3_Term,323_2_Project,323_1_Class Test,2_5_Mock Test,2_3_Term,2_2_Project,2_1_Class Test,2_4_Surprise Test" 
 default: "4_Surprise Test,3_Term,2_Project,1_Class Test"
quarter:
 numbers: "1"
 type: "325_1_Summer,325_2_Spring,325_3_Fall" 
 default: "0_N/A,1_1st Quarter,2_2nd Quarter,3_3rd Quarter,4_4th Quarter,3_First Term,3_Final Term"
mocktest:
 numbers: "2,323"
