school:
 upass: "Dear Parents, to login ClassTune (classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD# Helpline 01753467785 & 01740212121.Stay home, stay safe NPSND"
 epass: "Dear Student, to login ClassTune (classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. NPSND"
 feepaid: "Fees received BDT #AMOUNT# for #UNAME#(#UID#) as on #PAIDDATE# by TBL. TranID-#TRANID# TranRef-#TRANREF#, NPSND"
