school:
 upass: "To login College website (www.sagc.edu.bd) your User id: #UNAME# and new Password:#PASSWORD#, as given by institution Principal - SAGC"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. Principal, SAGC"
 feepaid: "Fees received BDT #AMOUNT# for #UNAME#(#UID#) as on #PAIDDATE# by TBL. TranID-#TRANID# TranRef-#TRANREF#, Sender - SAGC"
