school:
 upass: "To login College website (www.sagc.edu.bd) your User id: #UNAME# and new Password:#PASSWORD#, as given by institution Principal - SAGC"
 feature: "2_attandence,2_timetable_swap,296_attandence,319_attandence,312_attandence"
