school:
 upass: "Dear Parents, to login ClassTune (classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#"
 epass: "Dear Student, to login ClassTune (classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#"
 tpass: "Dear Employee, to login ClassTune (classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD# . ESS"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. ESS"
 feepaid: "Fees received BDT #AMOUNT# for #UNAME#(#UID#) as on #PAIDDATE# by TBL. TranID-#TRANID# TranRef-#TRANREF#, ESS"
