school:
 upass: "To login College website (www.sagc.edu.bd) your User id: #UNAME# and new Password:#PASSWORD#, as given by institution Principal - SAGC"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. Principal, SAGC"
