school:
 upass: "Dear Parents, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, as given by institution. BAGHC"
 epass: "Dear Parents, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, as given by institution. BAGHC"
 tpass: "Dear Emploee, to login ClassTune (https://classtune.com or mobile app) your User ID: #UNAME# & Password: #PASSWORD#, as given by institution. BAGHC"
 feedues: "Tuition Fee of January & Session Charge of #UNAME# ID #UID# is TK #AMOUNT#. Pay this amount within 28 Jan 2019 through online. BAGHC"
 feepaid: "Fees received BDT #AMOUNT# for #UNAME#(#UID#) as on #PAIDDATE# by TBL. TranID-#TRANID# TranRef-#TRANREF#, BAGHC"
