subjects:
 numbers: "87616,88373,88380,88387,88366,88394,87614,88371,88378,88385,88364,88392,87615,88372,88379,88386,88365,88393,87617,88374,88381,88388,88367,88395,87618,88375,88382,88389,88368,88396,87619,88376,88383,88390,88369,88397,87620,88377,88384,88391,88370,88398"
 group_87616: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87616: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88373: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88373: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88380: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88387: "History,Science,Geography"
 group_88366: "Art,Music,ICT,Physical Education"
 group_88394: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87614: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87614: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88371: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88371: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88378: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88385: "History,Science,Geography"
 group_88364: "Art,Music,ICT,Physical Education"
 group_88392: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87615: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87615: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88372: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88372: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88379: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88386: "History,Science,Geography"
 group_88365: "Art,Music,ICT,Physical Education"
 group_88393: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87617: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87617: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88374: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88374: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88381: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88388: "History,Science,Geography"
 group_88367: "Art,Music,ICT,Physical Education"
 group_88395: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87618: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87618: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88375: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88375: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88382: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88389: "History,Science,Geography"
 group_88368: "Art,Music,ICT,Physical Education"
 group_88396: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87619: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87619: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88376: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88376: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88383: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88390: "History,Science,Geography"
 group_88369: "Art,Music,ICT,Physical Education"
 group_88397: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"
 
 group_87620: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87620: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88377: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_88377: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_88384: "Recognition of Numbers,Counting,Writing,Mathematics-Addition/subtraction/multiplication/division,Understanding other mathematic concepts"
 group_88391: "History,Science,Geography"
 group_88370: "Art,Music,ICT,Physical Education"
 group_88398: "Follows school and class rules (including uniform),Handles conflicts appropriately,Organizes self material and belongings,Respect right diversity feelings and property of others,Respects school environment and materials,Punctual in school"