subjects:
 numbers: "87563,87570,87565,87572"
 group_87563: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87563: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_87570: "Art,Music,ICT,Physical Education"
 
 group_87565: "Speaking/Listening,Recognition,Writing,Reading"
 group_sub_87565: "Vocabulary,Structuring sent,Comprehension,Conversation and Pronunciation|Letter combinations/blends,Sounds of letter combinations/blends|Structuring sent,Spelling,Handwriting"
 group_87572: "Art,Music,ICT,Physical Education"