<?php

// File generated by the installatio wizard
// (do not modify manually)

return array(
    
    // Database settings
    
    'dbHost'     => 'localhost',
    'dbPort'     => 3306,
    'dbUser'     => 'champs21_champ',
    'dbPassword' => '1_84T~vADp2$',
    'dbName'     => 'champs21_school',
    
    // Chat application admin user
    
    'superUser' => 'admin',
    'superPass' => '15975321'
);

?>
