<div class="container" style="width: 77%;min-height:250px;">
    <div style="padding: 0px 22px 0 35px;" class="sports-inner-news yesPrint">    
        <div style="float:left;">
            <a href="<?php echo base_url('privacypolicy');?>">
                <h1 style="color:#93989C;" class="title noPrint f2">
                    Privacy Policy
                </h1>
            </a>
        </div>
        <div style="clear:both;"></div>
    </div>
    <div class="about-us">
        
        <p>Team Creative and its subsidiaries ('Champs21.com', also referred to in First Person in the subsequent paragraphs) respect your (the Subscriber's) privacy. This Privacy Policy provides succinctly the manner in which your personal data are collected and used by Team Creative. You (the Subscriber) are advised to please read the Privacy Policy carefully. By accessing the services provided by Team Creative, you agree to the collection and use of your data by Team Creative in the manner provided in this Privacy Policy.</p>
        <p>
            <ul>
                <li>1.	This Online Privacy Statement applies to data collected by Team Creative through its websites and services, as well as its offline product and support services. The Policy does not apply to the procedures and practices followed by entities that are not managed, owned or controlled by Team Creative or to the people that are not engaged, employed or managed by Team Creative. It also does not apply to the companies that Team Creative may acquire in future if such companies have their own, pre-existing privacy policies.</li>
                <li>2.	<b>Collection of Your Personal Information:</b> For offering our services at different levels, we may ask you to provide personal information, i.e., information that can be used to contact you or determine your specific identity, such as your e-mail address, name, home or work address or telephone number. We may also collect demographic information, such as your ZIP code, age, gender, preferences, interests and favorites.</li>
                <li>3.	To enable you to access some of our services, you will be asked to sign in with an e-mail address and password, which we refer to as your credentials. You can use the same credentials to sign and use different services of Team Creative. If you access our services via a mobile phone, you may use the same credentials to sign in.</li>
                <li>4.	For purposes of statistics, and also to refine our services, we may collect information about your visit, including the pages you view, the links you click and other actions taken in connection with Team Creative sites and services. Since we also deliver advertisements and provide website analytics of non- Team Creative sites and services, we may collect information about page views on these third party sites as well. Additionally, we may collect certain standard information that your browser sends to every website you visit, such as your IP address, browser type and language, access times and referring Web site addresses.</li>
                <li>5.	When you receive newsletters or promotional e-mail from Team Creative, we may use web beacons, customized links or similar technologies to determine whether the e-mail has been opened and which links you click in order to provide you more focused e-mail communications or other information.</li>
                <li>6.	In order to offer you a more consistent and personalized experience in your interactions with Team Creative, information collected through surveys may be combined with information obtained through other Champs21 services. We may also supplement the information we collect with information obtained from other companies. For example, we may use services from other companies that enable us to derive a general geographic area based on your IP address in order to customize certain services to your geographic area.</li>
                <li>7.	All such information pertaining to yourself or Children's Information (Please see below), gathered by us for the purposes described herein, is collectively referred to in this Statement as 'Personal Information'.</li>
                <li>8.	<b>Use of Your Personal Information:</b> Champs21 collects and uses your Personal Information to operate and improve its sites and deliver the services or carry out the transactions you have requested. These uses may include providing you with more effective customer service; making the sites or services easier to use by eliminating the need for you to repeatedly enter the same information; performing research and analysis aimed at improving our products, services and technologies; and displaying content and advertising that are customized to your interests and preferences.<br /><br />We may use some of the information we collect in order to personalize the ads we show you. However, we have designed our systems to select ads based only on data that do not personally and directly identify you. For example, we may select the ads we display according to certain general interest categories or segments based on demographic data, including any you may have provided when creating an account (e.g. age, zip or postal code, gender), general demographic data acquired from other companies, and a general geographic location derived from your IP address, the pages you view and links you click when using Team Creative and its partners' web sites and services.<br /><br />When we display personalized ads, we take a number of steps designed to protect your privacy. For example, we store page views, clicks and search terms used for ad personalization separately from your contact information or other data that directly identifies you (such as your name, e-mail address, etc.). Further, our technology and process keep a clear demarcation between your personal data and data collected through other means, preventing unauthorized correlation of this data.<br /><br />We also use your Personal Information to communicate with you. We may send certain mandatory service communications such as welcome letters, information on technical service issues, updates, events, periodic member letters and other related announcements. We may also occasionally send you product surveys or promotional mailings to inform you of other products or services available from Champs21 and its affiliates.<br /><br />Personal Information collected on Champs 21.com sites and services may be stored and processed in Bangladesh or any other country in which Team Creative or its affiliates, subsidiaries or agents maintain facilities, and by using a Champs 21 site or service, you consent to any such transfer of information outside of your country.</li>
                <li>9.	<b>Sharing of Your Personal Information:</b> Except as described in this statement, we will not disclose your Personal Information outside of Team Creative and its controlled subsidiaries and affiliates without your consent.<br /><br />Some of Team Creative services may be co-branded and offered in conjunction with another company. If you register for or use such services, both Team Creative and the other company may receive information collected in conjunction with the co-branded services.<br /><br />We occasionally hire other companies to provide limited services on our behalf, such as handling the processing and delivery of mailings, providing customer support, hosting websites, processing transactions, or performing statistical analysis of our services. Those companies will be permitted to obtain only the Personal Information they need to deliver the service. They are required to maintain the confidentiality of the information and are prohibited from using it for any other purpose.<br /><br />We may access and/or disclose your Personal Information if we believe such action is necessary to: (a) comply with the law or legal process served on Team Creative; (b) protect and defend the rights or property of Team Creative (including the enforcement of our agreements); or (c) act in urgent circumstances to protect the personal safety of users of Team Creative services or members of the public.</li>
                <li>10.	<b>Enforcement of This Privacy Statement:</b> If you have questions regarding this statement, you should first contact us by sending us mail on customercare@champs21.com. If you do not receive acknowledgement of your inquiry or your inquiry has not been satisfactorily addressed, you should then contact info@champs21.com</li>
                <li>11.	<b>Changes to This Privacy Statement:</b> We will occasionally update this privacy statement to reflect changes in our services and customer feedback. When we post changes to this Statement, we will revise the 'last updated' date at the top of this statement. If there are material changes to this statement or in how Team Creative will use your Personal Information, we will notify you either by prominently posting a notice of such changes prior to implementing the change or by directly sending you a notification. We encourage you to periodically review this statement to be informed of how Team Creative is protecting your information.</li>
                
            </ul>
        </p>
        
    </div>
</div>
<style>
.about-us
{
    background-color: #ffffff;
    margin: 0 20px;
    padding:20px;
    min-height: 500px;
}
</style>